version: "3"
services:
  slack-event-server:
    build:
      context: .
      dockerfile: ./slack-event-server/Dockerfile
    volumes:
      - ./slack-event-server:/app/slack-event-server
      - ./dbmgr:/app/dbmgr
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app_bridge
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www/certbot:/var/www/certbot
    networks:
      - app_bridge
  certbot:
    build: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www/certbot:/var/www/certbot
  web-server:
    build: ./web-server
    ports:
      - 9000:9000
    volumes:
      - ./web-server:/app/web-server

networks:
  app_bridge:
    driver: bridge
